[package]
name = "terrakit-console"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
readme.workspace = true

[dependencies]
terrakit-algorithms.workspace = true
terrakit-builtins.workspace = true
terrakit-core.workspace = true
terrakit-pipeline.workspace = true
terrakit-runtime.workspace = true
