[workspace]

[package]
name = "terrakit-console"
version = "0.0.1"
edition = "2024"
rust-version = "1.87"
publish = false

[dependencies]
terrakit-algorithms = { path = "../../generation/terrakit-algorithms" }
terrakit-builtins = { path = "../../generation/terrakit-builtins" }
terrakit-core = { path = "../../engine/terrakit-core" }
terrakit-pipeline = { path = "../../engine/terrakit-pipeline" }
terrakit-runtime = { path = "../../engine/terrakit-runtime" }