//! Immutable context supplied to every terrain stage execution.

use terrakit_core::{
    GenerationRegion, GenerationSeed, LodLevel, RegionDescriptor2, RegionDescriptor3, SeedDomain,
};

use crate::StageError;

/// Immutable deterministic data passed to every terrain stage.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct StageContext {
    /// Main generation seed for this pipeline execution.
    seed: GenerationSeed,

    /// Resolved region being generated by this pipeline execution.
    region: GenerationRegion,
}

impl StageContext {
    /// Creates a stage context from a main generation seed and resolved region.
    pub const fn new(seed: GenerationSeed, region: GenerationRegion) -> Self {
        Self { seed, region }
    }

    /// Creates a stage context from a raw integer seed and resolved region.
    pub const fn from_u64(seed: u64, region: GenerationRegion) -> Self {
        Self::new(GenerationSeed::new(seed), region)
    }

    /// Returns the canonical generation seed.
    pub const fn seed(&self) -> GenerationSeed {
        self.seed
    }

    /// Returns the resolved generation region.
    pub const fn region(&self) -> &GenerationRegion {
        &self.region
    }

    /// Returns the requested generation-detail level.
    ///
    /// This exposes the opaque tier selected by the region request, not a
    /// spatial scale or resolution divisor.
    pub const fn lod(&self) -> LodLevel {
        self.region.lod()
    }

    /// Returns the 2D region descriptor or a stage error for 3D contexts.
    pub fn region2(&self) -> Result<&RegionDescriptor2, StageError> {
        self.region
            .as_region2()
            .ok_or_else(|| StageError::new("stage context does not contain a 2D generation region"))
    }

    /// Returns the 3D region descriptor or a stage error for 2D contexts.
    pub fn region3(&self) -> Result<&RegionDescriptor3, StageError> {
        self.region
            .as_region3()
            .ok_or_else(|| StageError::new("stage context does not contain a 3D generation region"))
    }

    /// Derives a deterministic seed for a stage or algorithm domain.
    ///
    /// The result depends only on [`Self::seed`] and `domain`, not on execution
    /// order or global state.
    pub fn derive_seed(&self, domain: SeedDomain) -> GenerationSeed {
        self.seed.derive(domain)
    }

    /// Derives a deterministic raw seed for callers that still store domains
    /// as integers.
    pub fn derived_seed(&self, domain: u64) -> u64 {
        self.derive_seed(SeedDomain::new(domain)).value()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use terrakit_core::{
        Extent2, Extent3, LodLevel, RegionCoord2, RegionCoord3, RegionLayout2, RegionLayout3,
        RegionRequest2, RegionRequest3, Vector2F64, Vector3F64,
    };

    fn region2_at(lod: LodLevel) -> GenerationRegion {
        let layout =
            RegionLayout2::new(Extent2::try_new(4, 4).unwrap(), Vector2F64::new(1.0, 1.0)).unwrap();

        GenerationRegion::Region2(
            layout
                .resolve(RegionRequest2::new(RegionCoord2::new(2, -1), lod))
                .unwrap(),
        )
    }

    fn region2() -> GenerationRegion {
        region2_at(LodLevel::HIGHEST)
    }

    fn region3_at(lod: LodLevel) -> GenerationRegion {
        let layout = RegionLayout3::new(
            Extent3::try_new(4, 4, 4).unwrap(),
            Vector3F64::new(1.0, 1.0, 1.0),
        )
        .unwrap();

        GenerationRegion::Region3(
            layout
                .resolve(RegionRequest3::new(RegionCoord3::new(1, 2, 3), lod))
                .unwrap(),
        )
    }

    fn region3() -> GenerationRegion {
        region3_at(LodLevel::HIGHEST)
    }

    #[test]
    fn retains_canonical_seed() {
        let context = StageContext::new(GenerationSeed::new(123), region2());

        assert_eq!(context.seed(), GenerationSeed::new(123));
    }

    #[test]
    fn retains_2d_generation_region() {
        let region = region2();
        let context = StageContext::new(GenerationSeed::new(123), region);

        assert_eq!(context.region(), &region);
        assert_eq!(
            context.region2().unwrap().coordinate(),
            RegionCoord2::new(2, -1)
        );
    }

    #[test]
    fn retains_3d_generation_region() {
        let region = region3();
        let context = StageContext::new(GenerationSeed::new(123), region);

        assert_eq!(context.region(), &region);
        assert_eq!(
            context.region3().unwrap().coordinate(),
            RegionCoord3::new(1, 2, 3)
        );
    }

    #[test]
    fn exposes_requested_lod_for_2d_generation_region() {
        let lod = LodLevel::new(2);
        let context = StageContext::new(GenerationSeed::new(123), region2_at(lod));

        assert_eq!(context.lod(), lod);
    }

    #[test]
    fn exposes_requested_lod_for_3d_generation_region() {
        let lod = LodLevel::new(1);
        let context = StageContext::new(GenerationSeed::new(123), region3_at(lod));

        assert_eq!(context.lod(), lod);
    }

    #[test]
    fn typed_region_access_fails_safely_for_wrong_dimensionality() {
        let context2 = StageContext::new(GenerationSeed::new(123), region2());
        let context3 = StageContext::new(GenerationSeed::new(123), region3());

        assert!(context2.region3().unwrap_err().message().contains("3D"));
        assert!(context3.region2().unwrap_err().message().contains("2D"));
    }

    #[test]
    fn derived_seeds_are_deterministic() {
        let context = StageContext::from_u64(123, region2());
        let domain = SeedDomain::new(7);

        assert_eq!(context.derive_seed(domain), context.derive_seed(domain));
    }

    #[test]
    fn different_domains_normally_produce_different_seeds() {
        let context = StageContext::from_u64(123, region2());

        assert_ne!(
            context.derive_seed(SeedDomain::new(7)),
            context.derive_seed(SeedDomain::new(8))
        );
    }

    #[test]
    fn deriving_seed_does_not_mutate_context() {
        let context = StageContext::from_u64(123, region2());
        let original = context;

        let _ = context.derive_seed(SeedDomain::new(7));

        assert_eq!(context, original);
    }

    #[test]
    fn raw_seed_convenience_delegates_to_core_seed_derivation() {
        let context = StageContext::from_u64(123, region2());

        assert_eq!(
            context.derived_seed(7),
            GenerationSeed::new(123).derive(SeedDomain::new(7)).value()
        );
    }
}
