[package]
name = "terrakit-c-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
readme.workspace = true

[lib]
name = "terrakit"
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
terrakit-core.workspace = true
terrakit-pipeline.workspace = true
terrakit-runtime.workspace = true
terrakit-builtins.workspace = true
