#ifndef TERRAKIT_H
#define TERRAKIT_H

/* Generated by cbindgen for TerraKit. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#ifndef TK_API
#  if defined(_WIN32) && defined(TK_BUILD_SHARED)
#    define TK_API __declspec(dllexport)
#  elif defined(_WIN32) && defined(TK_USE_SHARED)
#    define TK_API __declspec(dllimport)
#  else
#    define TK_API
#  endif
#endif


/**
 * Opaque generation result handle.
 */
typedef struct tk_generation_result_t tk_generation_result_t;

/**
 * Opaque completed pipeline handle.
 */
typedef struct tk_pipeline_t tk_pipeline_t;

/**
 * Opaque pipeline assembler handle.
 */
typedef struct tk_pipeline_assembler_t tk_pipeline_assembler_t;

/**
 * Opaque synchronous runtime handle.
 */
typedef struct tk_runtime_t tk_runtime_t;

/**
 * Opaque stage construction handle.
 */
typedef struct tk_stage_construction_t tk_stage_construction_t;

/**
 * Opaque stage registry handle.
 */
typedef struct tk_stage_registry_t tk_stage_registry_t;

/**
 * ABI status code returned by fallible TerraKit C API functions.
 */
typedef int32_t tk_status_t;

/**
 * Borrowed UTF-8 string view.
 */
typedef struct tk_string_view_t {
  /**
   * Pointer to UTF-8 bytes, not necessarily NUL-terminated.
   */
  const char *data;
  /**
   * Number of bytes available at `data`.
   */
  size_t length;
} tk_string_view_t;

/**
 * ABI parameter-kind tag.
 */
typedef int32_t tk_parameter_kind_t;

/**
 * ABI boolean value. Valid values are `TK_FALSE` and `TK_TRUE`.
 */
typedef uint8_t tk_bool_t;

/**
 * C-layout two-component 64-bit vector.
 */
typedef struct tk_vec2_f64_t {
  /**
   * X component.
   */
  double x;
  /**
   * Y component.
   */
  double y;
} tk_vec2_f64_t;

/**
 * C-layout three-component 64-bit vector.
 */
typedef struct tk_vec3_f64_t {
  /**
   * X component.
   */
  double x;
  /**
   * Y component.
   */
  double y;
  /**
   * Z component.
   */
  double z;
} tk_vec3_f64_t;

/**
 * Tagged ABI parameter value.
 */
typedef struct tk_parameter_value_t {
  /**
   * Active value kind.
   */
  tk_parameter_kind_t kind;
  /**
   * Boolean value for `TK_PARAMETER_KIND_BOOL`.
   */
  tk_bool_t bool_value;
  /**
   * Reserved boolean padding bytes. Must be zero.
   */
  uint8_t reserved_bool[3];
  /**
   * Signed integer value for `TK_PARAMETER_KIND_I64`.
   */
  int64_t i64_value;
  /**
   * Unsigned integer value for `TK_PARAMETER_KIND_U64`.
   */
  uint64_t u64_value;
  /**
   * 32-bit float value for `TK_PARAMETER_KIND_F32`.
   */
  float f32_value;
  /**
   * Reserved float padding. Must be zero.
   */
  uint32_t reserved_f32;
  /**
   * 64-bit float value for `TK_PARAMETER_KIND_F64`.
   */
  double f64_value;
  /**
   * Two-component vector value for `TK_PARAMETER_KIND_VECTOR2_F64`.
   */
  struct tk_vec2_f64_t vector2_f64_value;
  /**
   * Three-component vector value for `TK_PARAMETER_KIND_VECTOR3_F64`.
   */
  struct tk_vec3_f64_t vector3_f64_value;
  /**
   * UTF-8 text for string and enum values.
   */
  struct tk_string_view_t text_value;
} tk_parameter_value_t;

/**
 * Discoverable metadata for one stage schema.
 */
typedef struct tk_stage_schema_info_t {
  /**
   * Stable stage type identifier.
   */
  struct tk_string_view_t type_id;
  /**
   * Stage schema version.
   */
  uint32_t schema_version;
  /**
   * User-facing stage name.
   */
  struct tk_string_view_t display_name;
  /**
   * User-facing category label.
   */
  struct tk_string_view_t category;
  /**
   * User-facing description.
   */
  struct tk_string_view_t description;
  /**
   * Number of input ports.
   */
  size_t input_count;
  /**
   * Number of output ports.
   */
  size_t output_count;
  /**
   * Number of editable parameters.
   */
  size_t parameter_count;
} tk_stage_schema_info_t;

/**
 * ABI resource-kind tag.
 */
typedef int32_t tk_resource_kind_t;

/**
 * Discoverable metadata for one input port.
 */
typedef struct tk_input_port_info_t {
  /**
   * Stable local port identifier.
   */
  struct tk_string_view_t id;
  /**
   * User-facing port name.
   */
  struct tk_string_view_t display_name;
  /**
   * User-facing description.
   */
  struct tk_string_view_t description;
  /**
   * Accepted resource kind.
   */
  tk_resource_kind_t resource_kind;
  /**
   * Nonzero when the input may be unbound.
   */
  tk_bool_t optional;
} tk_input_port_info_t;

/**
 * Discoverable metadata for one output port.
 */
typedef struct tk_output_port_info_t {
  /**
   * Stable local port identifier.
   */
  struct tk_string_view_t id;
  /**
   * User-facing port name.
   */
  struct tk_string_view_t display_name;
  /**
   * User-facing description.
   */
  struct tk_string_view_t description;
  /**
   * Produced resource kind.
   */
  tk_resource_kind_t resource_kind;
} tk_output_port_info_t;

/**
 * Discoverable parameter metadata, defaults, bounds, and enum option count.
 */
typedef struct tk_parameter_info_t {
  /**
   * Stable parameter identifier.
   */
  struct tk_string_view_t id;
  /**
   * User-facing parameter name.
   */
  struct tk_string_view_t display_name;
  /**
   * User-facing description.
   */
  struct tk_string_view_t description;
  /**
   * Accepted parameter kind.
   */
  tk_parameter_kind_t kind;
  /**
   * Nonzero when a default value is present.
   */
  tk_bool_t has_default;
  /**
   * Default value when `has_default` is `TK_TRUE`.
   */
  struct tk_parameter_value_t default_value;
  /**
   * Nonzero when a numeric minimum exists.
   */
  tk_bool_t has_minimum;
  /**
   * Inclusive numeric minimum when present.
   */
  struct tk_parameter_value_t minimum_value;
  /**
   * Nonzero when a numeric maximum exists.
   */
  tk_bool_t has_maximum;
  /**
   * Inclusive numeric maximum when present.
   */
  struct tk_parameter_value_t maximum_value;
  /**
   * Number of enum options for enum parameters.
   */
  size_t enum_option_count;
} tk_parameter_info_t;

/**
 * Discoverable metadata for one enum option.
 */
typedef struct tk_enum_option_info_t {
  /**
   * Stable enum-option identifier.
   */
  struct tk_string_view_t id;
  /**
   * User-facing option name.
   */
  struct tk_string_view_t display_name;
  /**
   * User-facing description.
   */
  struct tk_string_view_t description;
} tk_enum_option_info_t;

/**
 * ABI region-kind tag.
 */
typedef int32_t tk_region_kind_t;

/**
 * C-layout 2D grid-to-world transform.
 */
typedef struct tk_grid_transform_2_t {
  /**
   * World-space grid origin.
   */
  struct tk_vec3_f64_t origin;
  /**
   * World-space axis for increasing grid X.
   */
  struct tk_vec3_f64_t axis_x;
  /**
   * World-space axis for increasing grid Y.
   */
  struct tk_vec3_f64_t axis_y;
} tk_grid_transform_2_t;

/**
 * Resolved 2D region information returned by a generation result.
 */
typedef struct tk_region_2d_info_t {
  /**
   * Region coordinate X.
   */
  int64_t region_x;
  /**
   * Region coordinate Y.
   */
  int64_t region_y;
  /**
   * Opaque generation-detail tier.
   */
  uint16_t lod_level;
  /**
   * Reserved bytes. Always zero on output.
   */
  uint8_t reserved[6];
  /**
   * Resolved cell-sample width.
   */
  uint32_t cell_width;
  /**
   * Resolved cell-sample height.
   */
  uint32_t cell_height;
  /**
   * Resolved point-sample width.
   */
  uint32_t point_width;
  /**
   * Resolved point-sample height.
   */
  uint32_t point_height;
  /**
   * Resolved effective point spacing.
   */
  struct tk_vec2_f64_t effective_spacing;
  /**
   * Resolved grid-to-world transform.
   */
  struct tk_grid_transform_2_t transform;
} tk_region_2d_info_t;

/**
 * C-layout 3D grid-to-world transform.
 */
typedef struct tk_grid_transform_3_t {
  /**
   * World-space grid origin.
   */
  struct tk_vec3_f64_t origin;
  /**
   * World-space axis for increasing grid X.
   */
  struct tk_vec3_f64_t axis_x;
  /**
   * World-space axis for increasing grid Y.
   */
  struct tk_vec3_f64_t axis_y;
  /**
   * World-space axis for increasing grid Z.
   */
  struct tk_vec3_f64_t axis_z;
} tk_grid_transform_3_t;

/**
 * Resolved 3D region information returned by a generation result.
 */
typedef struct tk_region_3d_info_t {
  /**
   * Region coordinate X.
   */
  int64_t region_x;
  /**
   * Region coordinate Y.
   */
  int64_t region_y;
  /**
   * Region coordinate Z.
   */
  int64_t region_z;
  /**
   * Opaque generation-detail tier.
   */
  uint16_t lod_level;
  /**
   * Reserved bytes. Always zero on output.
   */
  uint8_t reserved[6];
  /**
   * Resolved cell-sample width.
   */
  uint32_t cell_width;
  /**
   * Resolved cell-sample height.
   */
  uint32_t cell_height;
  /**
   * Resolved cell-sample depth.
   */
  uint32_t cell_depth;
  /**
   * Reserved output extent field. Always zero.
   */
  uint32_t reserved_extent;
  /**
   * Resolved point-sample width.
   */
  uint32_t point_width;
  /**
   * Resolved point-sample height.
   */
  uint32_t point_height;
  /**
   * Resolved point-sample depth.
   */
  uint32_t point_depth;
  /**
   * Reserved output point extent field. Always zero.
   */
  uint32_t reserved_point_extent;
  /**
   * Resolved effective point spacing.
   */
  struct tk_vec3_f64_t effective_spacing;
  /**
   * Resolved grid-to-world transform.
   */
  struct tk_grid_transform_3_t transform;
} tk_region_3d_info_t;

/**
 * ABI sampling-domain tag.
 */
typedef int32_t tk_sampling_domain_t;

/**
 * Borrowed immutable height-field view.
 */
typedef struct tk_height_field_view_t {
  /**
   * Height-field sample width.
   */
  uint32_t width;
  /**
   * Height-field sample height.
   */
  uint32_t height;
  /**
   * Sampling-domain tag.
   */
  tk_sampling_domain_t sampling;
  /**
   * Reserved output field. Always zero.
   */
  uint32_t reserved;
  /**
   * Base grid transform.
   */
  struct tk_grid_transform_2_t transform;
  /**
   * Height displacement axis.
   */
  struct tk_vec3_f64_t height_axis;
  /**
   * Borrowed contiguous sample pointer.
   */
  const float *values;
  /**
   * Number of samples at `values`.
   */
  size_t value_count;
} tk_height_field_view_t;

/**
 * Borrowed immutable density-field view.
 */
typedef struct tk_density_field_view_t {
  /**
   * Density-field sample width.
   */
  uint32_t width;
  /**
   * Density-field sample height.
   */
  uint32_t height;
  /**
   * Density-field sample depth.
   */
  uint32_t depth;
  /**
   * Reserved output extent field. Always zero.
   */
  uint32_t reserved_extent;
  /**
   * Sampling-domain tag.
   */
  tk_sampling_domain_t sampling;
  /**
   * Reserved output sampling field. Always zero.
   */
  uint32_t reserved_sampling;
  /**
   * Grid transform.
   */
  struct tk_grid_transform_3_t transform;
  /**
   * Borrowed contiguous sample pointer.
   */
  const float *values;
  /**
   * Number of samples at `values`.
   */
  size_t value_count;
} tk_density_field_view_t;

/**
 * Borrowed immutable voxel-volume view.
 */
typedef struct tk_voxel_volume_view_t {
  /**
   * Voxel-volume sample width.
   */
  uint32_t width;
  /**
   * Voxel-volume sample height.
   */
  uint32_t height;
  /**
   * Voxel-volume sample depth.
   */
  uint32_t depth;
  /**
   * Reserved output extent field. Always zero.
   */
  uint32_t reserved_extent;
  /**
   * Sampling-domain tag.
   */
  tk_sampling_domain_t sampling;
  /**
   * Reserved output sampling field. Always zero.
   */
  uint32_t reserved_sampling;
  /**
   * Grid transform.
   */
  struct tk_grid_transform_3_t transform;
  /**
   * Borrowed contiguous raw voxel ID pointer.
   */
  const uint32_t *values;
  /**
   * Number of voxel IDs at `values`.
   */
  size_t value_count;
} tk_voxel_volume_view_t;

/**
 * C-layout three-component 32-bit vector.
 */
typedef struct tk_vec3_f32_t {
  /**
   * X component.
   */
  float x;
  /**
   * Y component.
   */
  float y;
  /**
   * Z component.
   */
  float z;
} tk_vec3_f32_t;

/**
 * C-layout two-component 32-bit vector.
 */
typedef struct tk_vec2_f32_t {
  /**
   * X component.
   */
  float x;
  /**
   * Y component.
   */
  float y;
} tk_vec2_f32_t;

/**
 * Borrowed immutable terrain-mesh view.
 */
typedef struct tk_terrain_mesh_view_t {
  /**
   * High-precision world origin for local vertex buffers.
   */
  struct tk_vec3_f64_t origin;
  /**
   * Borrowed local-position pointer.
   */
  const struct tk_vec3_f32_t *positions;
  /**
   * Number of positions.
   */
  size_t position_count;
  /**
   * Borrowed triangle-index pointer.
   */
  const uint32_t *indices;
  /**
   * Number of triangle indices.
   */
  size_t index_count;
  /**
   * Optional borrowed normal pointer.
   */
  const struct tk_vec3_f32_t *normals;
  /**
   * Number of normals, or zero when absent.
   */
  size_t normal_count;
  /**
   * Optional borrowed texture-coordinate pointer.
   */
  const struct tk_vec2_f32_t *texcoords;
  /**
   * Number of texture coordinates, or zero when absent.
   */
  size_t texcoord_count;
} tk_terrain_mesh_view_t;

/**
 * 2D region layout for runtime creation.
 */
typedef struct tk_region_layout_2d_t {
  /**
   * Highest-detail cell width.
   */
  uint32_t cell_width;
  /**
   * Highest-detail cell height.
   */
  uint32_t cell_height;
  /**
   * Highest-detail cell spacing.
   */
  struct tk_vec2_f64_t base_spacing;
} tk_region_layout_2d_t;

/**
 * 3D region layout for runtime creation.
 */
typedef struct tk_region_layout_3d_t {
  /**
   * Highest-detail cell width.
   */
  uint32_t cell_width;
  /**
   * Highest-detail cell height.
   */
  uint32_t cell_height;
  /**
   * Highest-detail cell depth.
   */
  uint32_t cell_depth;
  /**
   * Reserved field. Must be zero.
   */
  uint32_t reserved;
  /**
   * Highest-detail cell spacing.
   */
  struct tk_vec3_f64_t base_spacing;
} tk_region_layout_3d_t;

/**
 * Per-call 2D generation request.
 */
typedef struct tk_generation_request_2d_t {
  /**
   * Deterministic generation seed.
   */
  uint64_t seed;
  /**
   * Region coordinate X.
   */
  int64_t region_x;
  /**
   * Region coordinate Y.
   */
  int64_t region_y;
  /**
   * Opaque generation-detail tier.
   */
  uint16_t lod_level;
  /**
   * Reserved bytes. Must be zero.
   */
  uint8_t reserved[6];
} tk_generation_request_2d_t;

/**
 * Per-call 3D generation request.
 */
typedef struct tk_generation_request_3d_t {
  /**
   * Deterministic generation seed.
   */
  uint64_t seed;
  /**
   * Region coordinate X.
   */
  int64_t region_x;
  /**
   * Region coordinate Y.
   */
  int64_t region_y;
  /**
   * Region coordinate Z.
   */
  int64_t region_z;
  /**
   * Opaque generation-detail tier.
   */
  uint16_t lod_level;
  /**
   * Reserved bytes. Must be zero.
   */
  uint8_t reserved[6];
} tk_generation_request_3d_t;

/**
 * C-layout semantic version.
 */
typedef struct tk_version_t {
  /**
   * Major version component.
   */
  uint32_t major;
  /**
   * Minor version component.
   */
  uint32_t minor;
  /**
   * Patch version component.
   */
  uint32_t patch;
} tk_version_t;

/**
 * False ABI boolean value.
 */
#define TK_FALSE 0

/**
 * True ABI boolean value.
 */
#define TK_TRUE 1

/**
 * Successful call.
 */
#define TK_STATUS_OK 0

/**
 * A required pointer argument was null.
 */
#define TK_STATUS_NULL_ARGUMENT 1

/**
 * A value was malformed or structurally invalid.
 */
#define TK_STATUS_INVALID_ARGUMENT 2

/**
 * A string view did not contain UTF-8.
 */
#define TK_STATUS_INVALID_UTF8 3

/**
 * A numeric value or index was outside the accepted range.
 */
#define TK_STATUS_OUT_OF_RANGE 4

/**
 * A requested schema, port, parameter, enum option, or resource was missing.
 */
#define TK_STATUS_NOT_FOUND 5

/**
 * A parameter, resource, request, or view had the wrong kind.
 */
#define TK_STATUS_TYPE_MISMATCH 6

/**
 * A stage construction requested a schema version that is not registered.
 */
#define TK_STATUS_SCHEMA_VERSION_MISMATCH 7

/**
 * A registry, binding, parameter, or pipeline configuration failed.
 */
#define TK_STATUS_CONFIGURATION_ERROR 8

/**
 * Runtime generation failed while executing a pipeline.
 */
#define TK_STATUS_GENERATION_ERROR 9

/**
 * The caller-provided copy buffer was too small.
 */
#define TK_STATUS_BUFFER_TOO_SMALL 10

/**
 * A panic or impossible internal state was caught at the ABI boundary.
 */
#define TK_STATUS_INTERNAL_ERROR 255

/**
 * Invalid or unknown region kind.
 */
#define TK_REGION_KIND_INVALID 0

/**
 * Two-dimensional region kind.
 */
#define TK_REGION_KIND_REGION_2 1

/**
 * Three-dimensional region kind.
 */
#define TK_REGION_KIND_REGION_3 2

/**
 * Invalid or unknown resource kind.
 */
#define TK_RESOURCE_KIND_INVALID 0

/**
 * Height-field resource kind.
 */
#define TK_RESOURCE_KIND_HEIGHT_FIELD 1

/**
 * Density-field resource kind.
 */
#define TK_RESOURCE_KIND_DENSITY_FIELD 2

/**
 * Voxel-volume resource kind.
 */
#define TK_RESOURCE_KIND_VOXEL_VOLUME 3

/**
 * Terrain-mesh resource kind.
 */
#define TK_RESOURCE_KIND_MESH 4

/**
 * Invalid or unknown sampling domain.
 */
#define TK_SAMPLING_DOMAIN_INVALID 0

/**
 * Point-sampled domain.
 */
#define TK_SAMPLING_DOMAIN_POINTS 1

/**
 * Cell-sampled domain.
 */
#define TK_SAMPLING_DOMAIN_CELLS 2

/**
 * Invalid or unknown parameter kind.
 */
#define TK_PARAMETER_KIND_INVALID 0

/**
 * Boolean parameter kind.
 */
#define TK_PARAMETER_KIND_BOOL 1

/**
 * Signed 64-bit integer parameter kind.
 */
#define TK_PARAMETER_KIND_I64 2

/**
 * Unsigned 64-bit integer parameter kind.
 */
#define TK_PARAMETER_KIND_U64 3

/**
 * 32-bit float parameter kind.
 */
#define TK_PARAMETER_KIND_F32 4

/**
 * 64-bit float parameter kind.
 */
#define TK_PARAMETER_KIND_F64 5

/**
 * Two-component `f64` vector parameter kind.
 */
#define TK_PARAMETER_KIND_VECTOR2_F64 6

/**
 * Three-component `f64` vector parameter kind.
 */
#define TK_PARAMETER_KIND_VECTOR3_F64 7

/**
 * UTF-8 string parameter kind.
 */
#define TK_PARAMETER_KIND_STRING 8

/**
 * Stable enum-option identifier parameter kind.
 */
#define TK_PARAMETER_KIND_ENUM 9

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Creates an owned stage construction handle.
 */
TK_API
tk_status_t tk_stage_construction_create(uint64_t stage_id,
                                         struct tk_string_view_t stage_type_id,
                                         uint32_t schema_version,
                                         struct tk_stage_construction_t **out_construction);

/**
 * Destroys a stage construction handle.
 */
TK_API tk_status_t tk_stage_construction_destroy(struct tk_stage_construction_t **construction);

/**
 * Inserts or replaces one parameter value on a stage construction.
 */
TK_API
tk_status_t tk_stage_construction_set_parameter(struct tk_stage_construction_t *construction,
                                                struct tk_string_view_t parameter_id,
                                                const struct tk_parameter_value_t *value);

/**
 * Binds one input port to a caller-assigned resource key.
 */
TK_API
tk_status_t tk_stage_construction_bind_input(struct tk_stage_construction_t *construction,
                                             struct tk_string_view_t port_id,
                                             uint64_t resource_key);

/**
 * Binds one output port to a caller-assigned resource key.
 */
TK_API
tk_status_t tk_stage_construction_bind_output(struct tk_stage_construction_t *construction,
                                              struct tk_string_view_t port_id,
                                              uint64_t resource_key);

/**
 * Clears the thread-local ABI diagnostic message.
 */
TK_API void tk_clear_last_error(void);

/**
 * Copies the thread-local ABI diagnostic message into a caller buffer.
 *
 * # Safety
 *
 * Any non-null `buffer` must point to caller-owned writable storage of at
 * least `capacity` bytes, and any non-null `out_required` must point to
 * caller-owned writable storage for one `usize`.
 */
TK_API tk_status_t tk_last_error_message_copy(char *buffer, size_t capacity, size_t *out_required);

/**
 * Creates a pipeline assembler that retains the registry independently.
 */
TK_API
tk_status_t tk_pipeline_assembler_create(const struct tk_stage_registry_t *registry,
                                         struct tk_pipeline_assembler_t **out_assembler);

/**
 * Destroys a pipeline assembler handle.
 */
TK_API tk_status_t tk_pipeline_assembler_destroy(struct tk_pipeline_assembler_t **assembler);

/**
 * Validates and moves one construction into the assembler's ordered list.
 */
TK_API
tk_status_t tk_pipeline_assembler_add_stage(struct tk_pipeline_assembler_t *assembler,
                                            struct tk_stage_construction_t **construction);

/**
 * Consumes an assembler and returns a completed pipeline.
 */
TK_API
tk_status_t tk_pipeline_assembler_finish(struct tk_pipeline_assembler_t **assembler,
                                         struct tk_pipeline_t **out_pipeline);

/**
 * Destroys a completed pipeline handle.
 */
TK_API tk_status_t tk_pipeline_destroy(struct tk_pipeline_t **pipeline);

/**
 * Creates an immutable registry populated with TerraKit built-in stage definitions.
 */
TK_API tk_status_t tk_stage_registry_create_builtin(struct tk_stage_registry_t **out_registry);

/**
 * Destroys a stage registry handle.
 */
TK_API tk_status_t tk_stage_registry_destroy(struct tk_stage_registry_t **registry);

/**
 * Returns the number of schemas in deterministic registry order.
 */
TK_API
tk_status_t tk_stage_registry_get_schema_count(const struct tk_stage_registry_t *registry,
                                               size_t *out_count);

/**
 * Finds a schema index by stage type identifier.
 */
TK_API
tk_status_t tk_stage_registry_find_schema(const struct tk_stage_registry_t *registry,
                                          struct tk_string_view_t stage_type_id,
                                          size_t *out_schema_index);

/**
 * Returns one schema by deterministic registry index.
 */
TK_API
tk_status_t tk_stage_registry_get_schema(const struct tk_stage_registry_t *registry,
                                         size_t schema_index,
                                         struct tk_stage_schema_info_t *out_schema);

/**
 * Returns one input port from a schema.
 */
TK_API
tk_status_t tk_stage_registry_get_input_port(const struct tk_stage_registry_t *registry,
                                             size_t schema_index,
                                             size_t input_index,
                                             struct tk_input_port_info_t *out_port);

/**
 * Returns one output port from a schema.
 */
TK_API
tk_status_t tk_stage_registry_get_output_port(const struct tk_stage_registry_t *registry,
                                              size_t schema_index,
                                              size_t output_index,
                                              struct tk_output_port_info_t *out_port);

/**
 * Returns one parameter definition from a schema.
 */
TK_API
tk_status_t tk_stage_registry_get_parameter(const struct tk_stage_registry_t *registry,
                                            size_t schema_index,
                                            size_t parameter_index,
                                            struct tk_parameter_info_t *out_parameter);

/**
 * Returns one enum option from an enum parameter.
 */
TK_API
tk_status_t tk_stage_registry_get_enum_option(const struct tk_stage_registry_t *registry,
                                              size_t schema_index,
                                              size_t parameter_index,
                                              size_t option_index,
                                              struct tk_enum_option_info_t *out_option);

/**
 * Destroys a generation result handle.
 */
TK_API tk_status_t tk_generation_result_destroy(struct tk_generation_result_t **result);

/**
 * Returns the dimensionality of a generation result.
 */
TK_API
tk_status_t tk_generation_result_get_region_kind(const struct tk_generation_result_t *result,
                                                 tk_region_kind_t *out_kind);

/**
 * Returns the generation seed used for a result.
 */
TK_API
tk_status_t tk_generation_result_get_seed(const struct tk_generation_result_t *result,
                                          uint64_t *out_seed);

/**
 * Returns the opaque LOD tier used for a result.
 */
TK_API
tk_status_t tk_generation_result_get_lod(const struct tk_generation_result_t *result,
                                         uint16_t *out_lod);

/**
 * Returns resolved 2D region metadata for a 2D result.
 */
TK_API
tk_status_t tk_generation_result_get_region_2d(const struct tk_generation_result_t *result,
                                               struct tk_region_2d_info_t *out_region);

/**
 * Returns resolved 3D region metadata for a 3D result.
 */
TK_API
tk_status_t tk_generation_result_get_region_3d(const struct tk_generation_result_t *result,
                                               struct tk_region_3d_info_t *out_region);

/**
 * Returns the canonical resource kind for a generated resource key.
 */
TK_API
tk_status_t tk_generation_result_get_resource_kind(const struct tk_generation_result_t *result,
                                                   uint64_t resource_key,
                                                   tk_resource_kind_t *out_kind);

/**
 * Returns a borrowed immutable height-field view for a generated resource.
 */
TK_API
tk_status_t tk_generation_result_get_height_field(const struct tk_generation_result_t *result,
                                                  uint64_t resource_key,
                                                  struct tk_height_field_view_t *out_view);

/**
 * Returns a borrowed immutable density-field view for a generated resource.
 */
TK_API
tk_status_t tk_generation_result_get_density_field(const struct tk_generation_result_t *result,
                                                   uint64_t resource_key,
                                                   struct tk_density_field_view_t *out_view);

/**
 * Returns a borrowed immutable voxel-volume view for a generated resource.
 */
TK_API
tk_status_t tk_generation_result_get_voxel_volume(const struct tk_generation_result_t *result,
                                                  uint64_t resource_key,
                                                  struct tk_voxel_volume_view_t *out_view);

/**
 * Returns a borrowed immutable terrain-mesh view for a generated resource.
 */
TK_API
tk_status_t tk_generation_result_get_mesh(const struct tk_generation_result_t *result,
                                          uint64_t resource_key,
                                          struct tk_terrain_mesh_view_t *out_view);

/**
 * Creates a synchronous 2D runtime, consuming the pipeline on success.
 */
TK_API
tk_status_t tk_runtime_create_2d(struct tk_pipeline_t **pipeline,
                                 const struct tk_region_layout_2d_t *layout,
                                 struct tk_runtime_t **out_runtime);

/**
 * Creates a synchronous 3D runtime, consuming the pipeline on success.
 */
TK_API
tk_status_t tk_runtime_create_3d(struct tk_pipeline_t **pipeline,
                                 const struct tk_region_layout_3d_t *layout,
                                 struct tk_runtime_t **out_runtime);

/**
 * Returns the dimensionality of a runtime.
 */
TK_API
tk_status_t tk_runtime_get_region_kind(const struct tk_runtime_t *runtime,
                                       tk_region_kind_t *out_kind);

/**
 * Runs one synchronous 2D generation request.
 */
TK_API
tk_status_t tk_runtime_generate_2d(struct tk_runtime_t *runtime,
                                   const struct tk_generation_request_2d_t *request,
                                   struct tk_generation_result_t **out_result);

/**
 * Runs one synchronous 3D generation request.
 */
TK_API
tk_status_t tk_runtime_generate_3d(struct tk_runtime_t *runtime,
                                   const struct tk_generation_request_3d_t *request,
                                   struct tk_generation_result_t **out_result);

/**
 * Destroys a runtime handle.
 */
TK_API tk_status_t tk_runtime_destroy(struct tk_runtime_t **runtime);

/**
 * Writes the embedding ABI version, currently `1.0.0`.
 */
TK_API tk_status_t tk_get_abi_version(struct tk_version_t *out_version);

/**
 * Writes the TerraKit Rust package version string.
 */
TK_API tk_status_t tk_get_library_version(struct tk_string_view_t *out_version);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TERRAKIT_H */
