name: Unity Sync

on:
  push:
    branches: [main]
  schedule:
    - cron: '41 3 * * *'
  workflow_dispatch:

jobs:
  sync:
    uses: ./.github/workflows/_component-sync.yml
    with:
      branch: unity
      component: TerraKit Unity
    secrets:
      automation_token: ${{ secrets.TERRAKIT_AUTOMATION_TOKEN }}
